server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: authuser-service
            uri: lb://EAD-AUTHUSER-SERVICE
            predicates:
              - Path=/ead-authuser/**
            filters:
              # Este filtro remove o '/ead-authuser' da URL original
              - RewritePath=/ead-authuser/(?<segment>.*), /${segment}
          
          - id: course-service
            uri: lb://EAD-COURSE-SERVICE
            predicates:
              - Path=/ead-course/**
            filters:
              - RewritePath=/ead-course/(?<segment>.*), /${segment}
