server:
  port: 8084

spring:
  application:
    name: ead-notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-notification
    username: postgres
    password: wete2808
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://unodvbxe:UCknjRCONEFvXVreG45wUdSdRtS5cr0G@woodpecker.rmq.cloudamqp.com/unodvbxe

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationcommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
        notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
