server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authuser-service
          uri: lb://EAD-AUTHUSER-SERVICE
          predicates:
            - Path=/ead-authuser/**
          filters:
            - StripPrefix=1